import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

type User = { id: string; email: string; role: "admin" | "member" };
type Workspace = { id: string; name: string; ownerId: string; agentConnected?: boolean; workspacePath?: string | null; platform?: string | null };
type Member = { workspaceId: string; userId: string; email: string; role: "owner" | "editor" | "viewer" };
type Token = { id: string; workspaceId: string; prefix: string; role: "owner" | "editor" | "viewer"; createdAt: number; revokedAt: number | null };
type Call = { id: string; tool: string; status: string; workspace: string | null; durationMs: number | null; error: string | null; createdAt: number };

const api = import.meta.env.VITE_API_URL ?? "";
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${api}${path}`, { ...init, credentials: "include", headers: { "content-type": "application/json", ...(init?.headers ?? {}) } }); if (!response.ok) { const body = await response.json().catch(() => ({})) as { error?: string }; throw new Error(body.error ?? `HTTP ${response.status}`); } return await response.json() as T; }

function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { onLogin(await request<User>("/api/auth/login", { method: "POST", body: JSON.stringify({ email, password }) })); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  return <main className="auth"><form className="panel" onSubmit={submit}><p className="eyebrow">M-TUNNEL</p><h1>登录管理台</h1><label>邮箱<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>密码<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required minLength={8} /></label>{error && <p className="error">{error}</p>}<button type="submit">登录</button></form></main>;
}

function App({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [selected, setSelected] = useState(""); const [members, setMembers] = useState<Member[]>([]); const [tokens, setTokens] = useState<Token[]>([]); const [calls, setCalls] = useState<Call[]>([]); const [users, setUsers] = useState<User[]>([]); const [newToken, setNewToken] = useState(""); const [error, setError] = useState(""); const [name, setName] = useState("");
  const load = async () => { try { const [ws, cs] = await Promise.all([request<Workspace[]>("/api/workspaces"), request<Call[]>("/api/tool-calls")]); setWorkspaces(ws); setCalls(cs); if (!selected && ws[0]) setSelected(ws[0].id); if (user.role === "admin") setUsers(await request<User[]>("/api/users")); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 5000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (!selected) return; Promise.all([request<Member[]>(`/api/workspaces/${selected}/members`), request<Token[]>(`/api/workspaces/${selected}/tokens`)]).then(([m, t]) => { setMembers(m); setTokens(t); }).catch((e: unknown) => setError(e instanceof Error ? e.message : String(e))); }, [selected]);
  const createWorkspace = async () => { try { const ws = await request<Workspace>("/api/workspaces", { method: "POST", body: JSON.stringify({ name }) }); setName(""); setSelected(ws.id); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  const createToken = async (role: Token["role"]) => { try { const result = await request<{ token: string }>(`/api/workspaces/${selected}/tokens`, { method: "POST", body: JSON.stringify({ role }) }); setNewToken(result.token); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  const updateUser = async (id: string, role: User["role"]) => { await request(`/api/users/${id}`, { method: "PATCH", body: JSON.stringify({ role }) }); await load(); };
  return <main><header><div><p className="eyebrow">M-TUNNEL</p><h1>Workspace MCP</h1><p className="muted">{user.email} · {user.role}</p></div><button className="secondary" onClick={() => { void request("/api/auth/logout", { method: "POST" }); onLogout(); }}>退出</button></header>
    {error && <p className="error">{error}</p>}<section className="grid"><article><p className="label">工作区</p><strong>{workspaces.length}</strong></article><article><p className="label">在线 Agent</p><strong>{workspaces.filter((w) => w.agentConnected).length}</strong></article><article><p className="label">请求记录</p><strong>{calls.length}</strong></article></section>
    <section className="panel"><div className="panel-title"><h2>工作区</h2><div><input placeholder="新工作区名称" value={name} onChange={(e) => setName(e.target.value)} /><button onClick={() => void createWorkspace()} disabled={!name}>创建</button></div></div><div className="workspace-list">{workspaces.map((workspace) => <button className={selected === workspace.id ? "selected" : ""} key={workspace.id} onClick={() => setSelected(workspace.id)}><b>{workspace.name}</b><span>{workspace.agentConnected ? "在线" : "离线"}{workspace.workspacePath ? ` · ${workspace.workspacePath}` : ""}</span></button>)}</div></section>
    {selected && <section className="columns"><article className="panel"><h2>Token</h2><div className="actions"><button onClick={() => void createToken("editor")}>创建编辑 Token</button><button className="secondary" onClick={() => void createToken("viewer")}>创建只读 Token</button></div>{newToken && <p className="secret"><b>仅显示一次：</b><code>{newToken}</code></p>}<table><thead><tr><th>前缀</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>{tokens.map((token) => <tr key={token.id}><td><code>{token.prefix}</code></td><td>{token.role}</td><td>{token.revokedAt ? "已撤销" : "有效"}</td><td>{!token.revokedAt && <button className="link" onClick={() => void request(`/api/workspaces/${selected}/tokens/${token.id}`, { method: "DELETE" }).then(load)}>撤销</button>}</td></tr>)}</tbody></table></article><article className="panel"><h2>成员</h2><table><thead><tr><th>邮箱</th><th>角色</th></tr></thead><tbody>{members.map((member) => <tr key={member.userId}><td>{member.email}</td><td>{member.role}</td></tr>)}</tbody></table></article></section>}
    {user.role === "admin" && <section className="panel"><h2>全局用户</h2><table><thead><tr><th>邮箱</th><th>角色</th><th>修改</th></tr></thead><tbody>{users.map((item) => <tr key={item.id}><td>{item.email}</td><td>{item.role}</td><td><select value={item.role} onChange={(e) => void updateUser(item.id, e.target.value as User["role"])}><option value="admin">admin</option><option value="member">member</option></select></td></tr>)}</tbody></table></section>}
    <section className="panel"><div className="panel-title"><h2>最近调用</h2><span>{error || "每 5 秒刷新"}</span></div><table><thead><tr><th>工具</th><th>工作区</th><th>状态</th><th>耗时</th><th>时间</th><th>错误</th></tr></thead><tbody>{calls.map((call) => <tr key={call.id}><td><code>{call.tool}</code></td><td>{workspaces.find((w) => w.id === call.workspace)?.name ?? "—"}</td><td><span className={`status ${call.status}`}>{call.status}</span></td><td>{call.durationMs ?? "—"} ms</td><td>{new Date(call.createdAt).toLocaleString()}</td><td>{call.error || "—"}</td></tr>)}</tbody></table></section>
  </main>;
}

function Root() { const [user, setUser] = useState<User | null>(null); useEffect(() => { request<User>("/api/auth/me").then(setUser).catch(() => setUser(null)); }, []); return user ? <App user={user} onLogout={() => setUser(null)} /> : <Login onLogin={setUser} />; }
createRoot(document.getElementById("root")!).render(<Root />);
